In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Boston_Housing.csv')

In [ ]:
df.head()

      CRIM    ZN  INDUS  CHAS    NOX  ...  PTRATIO       B  LSTAT  MEDV  Unnamed: 14
0  0.00632  18.0   2.31     0  0.538  ...     15.3  396.90   4.98  24.0          NaN
1  0.02731   0.0   7.07     0  0.469  ...     17.8  396.90   9.14  21.6          NaN
2  0.02729   0.0   7.07     0  0.469  ...     17.8  392.83   4.03  34.7          NaN
3  0.03237   0.0   2.18     0  0.458  ...     18.7  394.63   2.94  33.4          NaN
4  0.06905   0.0   2.18     0  0.458  ...     18.7  396.90   5.33  36.2          NaN

[5 rows x 15 columns]

In [ ]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV', 'Unnamed: 14'],
      dtype='object')

In [ ]:
cols_with_nans = df.isna().any()
cols_with_nans

CRIM           False
ZN             False
INDUS          False
CHAS           False
NOX            False
RM             False
AGE            False
DIS            False
RAD            False
TAX            False
PTRATIO        False
B              False
LSTAT          False
MEDV           False
Unnamed: 14     True
dtype: bool

In [ ]:
X = df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']]
y = df['MEDV']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 420)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y_test, y_pred)

3.918603998950097

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8204483439409708

In [ ]:
y_pred

array([ 8.4125444 , 25.41951575, 29.75501873, 13.01498145,  6.07075972,
       21.49080997, 13.4816138 , 17.31574903, 17.40325158, 12.60642196,
       22.52708881, 34.66446567, 20.61229937, 31.45331493, 22.65226252,
       13.16786892,  6.0947401 , 29.2488195 , 29.07807096, 30.26054079,
       21.38894749, 17.13820544, 25.52605069, 24.53821668, 21.24764917,
       13.47146916, 25.04557617, 20.4223825 , 26.23079682, 20.22005018,
       33.17368581, 22.53018438, 23.62112231, 25.13639705, 27.56306771,
       26.93910833, 12.68128677, 25.65122351, 19.47337603, 34.0183456 ,
       16.98189229, 20.29958987, 32.83884584, 19.29848878,  8.20250104,
       31.21966141, 44.69156904, 17.73786811, 16.19906789, 35.90184594,
       27.83964796, 24.13270004, 20.02693576, 40.52455759, 32.8086748 ,
       27.4663774 , 17.73853768, 23.62431394, 15.71062441, 18.66681854,
       18.48988537, 27.59950036, 17.20933928, 32.92515829, 30.96830661,
       22.41630061, 23.40961634, 16.64571613, 23.76666858, 18.86284782,
       28.23530513, 34.82603848, 31.51333969, 25.46179071, 20.85573376,
       24.63835105, 39.69317998, 30.96753195, 24.52009403, 22.11699303,
       18.74090902, 42.67858567, 25.86124884,  7.38532121, 28.10749971,
       26.05766571, 15.28190801, 21.73424935, 16.93564111,  2.04760938,
       22.95606076, 20.42443441, 36.52710188, 33.55099809, 25.20855919,
       18.32635602, 10.49360608, 21.85265293, 10.28424532, 13.30859021,
       36.44529809, 12.30391897])